# Generated by Django 3.1.7 on 2021-10-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=100, verbose_name='Имя характеристики')),
                ('feature_name', models.CharField(max_length=255, verbose_name='Наименование характеристики')),
                ('postfix_for_value', models.CharField(blank=True, help_text='Например "Часы работы" кt', max_length=20, null=True, verbose_name='Постфикс значения')),
                ('use_in_filter', models.BooleanField(default=False, verbose_name='Использавть в фильтрации товаров в шаблоне')),
                ('filter_type', models.CharField(choices=[('radio', 'радио'), ('checkbox', 'чекбокс')], default='checkbox', max_length=20, verbose_name='тип фильтра')),
                ('filter_mesasure', models.CharField(help_text='Единицей измерений  будет информация в скобках', max_length=50, verbose_name='Единица измерения для фильтра. Например "Издатель"')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainap.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatureValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Значение характеристики')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainap.category', verbose_name='Категория')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainap.productfeatures', unique=True, verbose_name='Характеристика')),
            ],
        ),
    ]
