# Generated by Django 3.1.7 on 2021-10-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainap', '0002_productfeatures_productfeaturevalidator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeatures',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfeaturevalidator',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfeaturevalidator',
            name='feature',
        ),
    ]
